# Generated by Django 5.0 on 2023-12-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kami_airlines_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('passenger_count', models.PositiveIntegerField()),
            ],
        ),
    ]
